<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "arrangementer"
 *
 * Auto generated by Extension Builder 2015-06-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Arrangementer',
	'description' => 'Arrangements plugin for DUK',
	'category' => 'plugin',
	'author' => 'Stefan Kreisberg, Michael Høier Clausen',
	'author_email' => 'stefan@shufflebee.dk, michael@duk.dk',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);